package org.openpandora.box.util

import java.util.Locale
import java.util.TimeZone

object Languages {
  val locales = Locale.getAvailableLocales.toSeq
  val codes = locales.map(_.toString)
  def names(curLocale: Locale) = locales.map(_.getDisplayName(curLocale))
  def namesAndCodes(curLocale: Locale) = (names(curLocale) zip codes).sortBy(_._1)
  def localesAndNames(curLocale: Locale) = (locales zip names(curLocale)).sortBy(_._2)
}

object TimeZones {
  val codes = TimeZone.getAvailableIDs.toSeq
  .filterNot(_.startsWith("SystemV/"))
  .filterNot(_.startsWith("Etc/"))
  .filter(_.length > 3)
  .sortBy(identity)
  val timeZones = codes.map(TimeZone.getTimeZone(_))
  def names(curLocale: Locale) = timeZones.map(_.getDisplayName(curLocale))
  def namesAndCodes(curLocale: Locale) = (names(curLocale) zip codes).sortBy(_._1)
  def timeZonesAndNames(curLocale: Locale) = (timeZones zip names(curLocale)).sortBy(_._2)
  val timeZonesAndCodes = (timeZones zip codes).sortBy(_._2)
}

object DotDesktopCategories extends Enumeration {
  val Accessibility = Value("Accessibility")
  val ActionGame = Value("ActionGame")
  val AdventureGame = Value("AdventureGame")
  val Amusement = Value("Amusement")
  val ArcadeGame = Value("ArcadeGame")
  val Archiving = Value("Archiving")
  val Art = Value("Art")
  val ArtificialIntelligence = Value("ArtificialIntelligence")
  val Astronomy = Value("Astronomy")
  val Audio = Value("Audio")
  val AudioVideo = Value("AudioVideo")
  val AudioVideoEditing = Value("AudioVideoEditing")
  val Biology = Value("Biology")
  val BlocksGame = Value("BlocksGame")
  val BoardGame = Value("BoardGame")
  val Building = Value("Building")
  val Calculator = Value("Calculator")
  val Calendar = Value("Calendar")
  val CardGame = Value("CardGame")
  val Chart = Value("Chart")
  val Chat = Value("Chat")
  val Chemistry = Value("Chemistry")
  val Clock = Value("Clock")
  val Compression = Value("Compression")
  val ComputerScience = Value("ComputerScience")
  val ConsoleOnly = Value("ConsoleOnly")
  val Construction = Value("Construction")
  val ContactManagement = Value("ContactManagement")
  val Core = Value("Core")
  val DataVisualization = Value("DataVisualization")
  val Database = Value("Database")
  val Debugger = Value("Debugger")
  val DesktopSettings = Value("DesktopSettings")
  val Development = Value("Development")
  val Dialup = Value("Dialup")
  val Dictionary = Value("Dictionary")
  val DiscBurning = Value("DiscBurning")
  val Documentation = Value("Documentation")
  val Economy = Value("Economy")
  val Education = Value("Education")
  val Electricity = Value("Electricity")
  val Electronics = Value("Electronics")
  val Email = Value("Email")
  val Emulator = Value("Emulator")
  val Engineering = Value("Engineering")
  val FileManager = Value("FileManager")
  val FileTools = Value("FileTools")
  val FileTransfer = Value("FileTransfer")
  val Filesystem = Value("Filesystem")
  val Finance = Value("Finance")
  val FlowChart = Value("FlowChart")
  val GNOME = Value("GNOME")
  val GTK = Value("GTK")
  val GUIDesigner = Value("GUIDesigner")
  val Game = Value("Game")
  val Geography = Value("Geography")
  val Geology = Value("Geology")
  val Geoscience = Value("Geoscience")
  val Graphics = Value("Graphics")
  val HamRadio = Value("HamRadio")
  val HardwareSettings = Value("HardwareSettings")
  val History = Value("History")
  val IDE = Value("IDE")
  val IRCClient = Value("IRCClient")
  val ImageProcessing = Value("ImageProcessing")
  val InstantMessaging = Value("InstantMessaging")
  val Java = Value("Java")
  val KDE = Value("KDE")
  val KidsGame = Value("KidsGame")
  val Languages = Value("Languages")
  val Literature = Value("Literature")
  val LogicGame = Value("LogicGame")
  val Math = Value("Math")
  val MedicalSoftware = Value("MedicalSoftware")
  val Midi = Value("Midi")
  val Mixer = Value("Mixer")
  val Monitor = Value("Monitor")
  val Motif = Value("Motif")
  val Music = Value("Music")
  val Network = Value("Network")
  val News = Value("News")
  val NumericalAnalysis = Value("NumericalAnalysis")
  val OCR = Value("OCR")
  val Office = Value("Office")
  val P2P = Value("P2P")
  val PDA = Value("PDA")
  val PackageManager = Value("PackageManager")
  val ParallelComputing = Value("ParallelComputing")
  val Photography = Value("Photography")
  val Physics = Value("Physics")
  val Player = Value("Player")
  val Presentation = Value("Presentation")
  val Printing = Value("Printing")
  val Profiling = Value("Profiling")
  val ProjectManagement = Value("ProjectManagement")
  val Publishing = Value("Publishing")
  val Qt = Value("Qt")
  val RasterGraphics = Value("RasterGraphics")
  val Recorder = Value("Recorder")
  val RemoteAccess = Value("RemoteAccess")
  val RevisionControl = Value("RevisionControl")
  val Robotics = Value("Robotics")
  val RolePlaying = Value("RolePlaying")
  val Scanning = Value("Scanning")
  val Science = Value("Science")
  val Security = Value("Security")
  val Sequencer = Value("Sequencer")
  val Settings = Value("Settings")
  val Simulation = Value("Simulation")
  val Sports = Value("Sports")
  val SportsGame = Value("SportsGame")
  val Spreadsheet = Value("Spreadsheet")
  val StrategyGame = Value("StrategyGame")
  val System = Value("System")
  val TV = Value("TV")
  val Telephony = Value("Telephony")
  val TelephonyTools = Value("TelephonyTools")
  val TerminalEmulator = Value("TerminalEmulator")
  val TextEditor = Value("TextEditor")
  val TextTools = Value("TextTools")
  val ThreeDGraphics = Value("3DGraphics")
  val Translation = Value("Translation")
  val Tuner = Value("Tuner")
  val TwoDGraphics = Value("2DGraphics")
  val Utility = Value("Utility")
  val VectorGraphics = Value("VectorGraphics")
  val Video = Value("Video")
  val VideoConference = Value("VideoConference")
  val Viewer = Value("Viewer")
  val WebBrowser = Value("WebBrowser")
  val WebDevelopment = Value("WebDevelopment")
  val WordProcessor = Value("WordProcessor")
}
